/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TnTxt {
    }
}
declare global {
    interface HTMLTnTxtElement extends Components.TnTxt, HTMLStencilElement {
    }
    var HTMLTnTxtElement: {
        prototype: HTMLTnTxtElement;
        new (): HTMLTnTxtElement;
    };
    interface HTMLElementTagNameMap {
        "tn-txt": HTMLTnTxtElement;
    }
}
declare namespace LocalJSX {
    interface TnTxt {
    }
    interface IntrinsicElements {
        "tn-txt": TnTxt;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tn-txt": LocalJSX.TnTxt & JSXBase.HTMLAttributes<HTMLTnTxtElement>;
        }
    }
}
